// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1o9S8Z8OnpR7pERROU7wdcjF6kHnKxog',
    appId: '1:822287256382:web:acbeb73ea27e275f473a6f',
    messagingSenderId: '822287256382',
    projectId: 'flutter-notes-4ea29',
    authDomain: 'flutter-notes-4ea29.firebaseapp.com',
    storageBucket: 'flutter-notes-4ea29.firebasestorage.app',
    measurementId: 'G-22KSW1V2WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTmaUsa2P8rMQHOr1DKj6ZAOwoA8Z4-cQ',
    appId: '1:822287256382:android:3e1f194098e6fe5b473a6f',
    messagingSenderId: '822287256382',
    projectId: 'flutter-notes-4ea29',
    storageBucket: 'flutter-notes-4ea29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClZNqOkRHvxRALmWKO-4wkL6rcUyPk900',
    appId: '1:822287256382:ios:7129c9434e8ad923473a6f',
    messagingSenderId: '822287256382',
    projectId: 'flutter-notes-4ea29',
    storageBucket: 'flutter-notes-4ea29.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClZNqOkRHvxRALmWKO-4wkL6rcUyPk900',
    appId: '1:822287256382:ios:7129c9434e8ad923473a6f',
    messagingSenderId: '822287256382',
    projectId: 'flutter-notes-4ea29',
    storageBucket: 'flutter-notes-4ea29.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1o9S8Z8OnpR7pERROU7wdcjF6kHnKxog',
    appId: '1:822287256382:web:71b1fbee91cd91d9473a6f',
    messagingSenderId: '822287256382',
    projectId: 'flutter-notes-4ea29',
    authDomain: 'flutter-notes-4ea29.firebaseapp.com',
    storageBucket: 'flutter-notes-4ea29.firebasestorage.app',
    measurementId: 'G-JVTDTF8XY7',
  );
}
